version: '3'
services:
  elasticsearch0:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch0
    restart: always
    environment:
      - cluster.name=elastic-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
        docker_net:
          ipv4_address: ${ELASTIC_0_IP}

  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch1
    restart: always
    environment:
      - cluster.name=elastic-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch0"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
        docker_net:
          ipv4_address: ${ELASTIC_1_IP}

  backend0:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    container_name: backend0
    restart: always
    volumes:
        - "./backend/:/app"
    depends_on:
      - elasticsearch0
      - elasticsearch1
    networks:
      docker_net:
        ipv4_address: ${BE_0_IP}

  backend1:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    container_name: backend1
    restart: always
    volumes:
        - "./backend/:/app"
    depends_on:
      - elasticsearch0
      - elasticsearch1
    networks:
      docker_net:
        ipv4_address: ${BE_1_IP}

  frontend0:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    container_name: frontend0
    restart: always
    volumes:
        - "./frontend:/app"
    depends_on:
      - backend0
      - backend1
    networks:
      docker_net:
        ipv4_address: ${FE_0_IP}

  frontend1:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    container_name: frontend1
    restart: always
    volumes:
        - "./frontend:/app"
    depends_on:
      - backend0
      - backend1
    networks:
      docker_net:
        ipv4_address: ${FE_1_IP}

  haproxy:
    build: ./haproxy
    container_name: haproxy
    restart: always
    depends_on:
      - elasticsearch0
      - elasticsearch1
      - frontend0
      - frontend1
      - backend0
      - backend1
    ports:
        - 8001:8001
        - 8002:8002
        - 9201:9201
    expose:
        - 8001
        - 8002
        - 9201
    networks:
        docker_net:
            ipv4_address: ${HA_PROXY_IP}
    environment:
        - BE_0_IP=${BE_0_IP}
        - BE_V1_0_IP=${BE_V1_0_IP}
        - BE_V1_1_IP=${BE_V1_1_IP}
        - BE_1_IP=${BE_1_IP}
        - FE_0_IP=${FE_0_IP}
        - FE_1_IP=${FE_1_IP}
        - ELASTIC_0_IP=${ELASTIC_0_IP}
        - ELASTIC_1_IP=${ELASTIC_1_IP}

networks:
  docker_net:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: ${NETWORK_SUBNET}
